name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}  # Auto-detects your username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated from v2 to v4
        with:
          name: snake-animation
          path: dist/
