name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:     # Cho phép chạy thủ công

permissions:
  contents: write       # Cần quyền này để commit thay đổi

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: thanhduong1311
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
